#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1549381618                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The easiest way to follow your favorite casters

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.


# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 


# Information About Yourself
your_name                                 : Murdo Connochie                             
your_link                                 : https://murdo.xyz                     
your_city                                 : Toronto 🇨🇦
email_address                             : murdo.connochie+scout@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Follow your favorite Farcasters
    description                           : Scout lets you follow specific Farcaster users by username or FID. Organize and manage their casts with powerful features like marking casts as read/unread, starring favorites, and filtering content to suit your needs.
    fontawesome_icon_name                 : user-plus
    
  - title                                 : Built for productivity
    description                           : With features like offline support, fast local caching, pull-to-refresh for the latest casts, and search functionality, Scout is your perfect companion for staying updated on Farcaster conversations.
    fontawesome_icon_name                 : bolt

  - title                                 : Customizable for you
    description                           : Scout offers filters to hide replies, recasts, media-only posts, or URL-less posts. You can even choose between the menu or an all-casts feed as your default view, and load up to 50 historical casts from the last 30 days when adding new users.
    fontawesome_icon_name                 : gear

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#4183C4"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#4183C4"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
