#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1549381618                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The easiest way to follow your favorite casters

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.


# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 


# Information About Yourself
your_name                                 : Murdo Connochie                             
your_link                                 : https://murdo.xyz                     
your_city                                 : Toronto 🇨🇦
email_address                             : murdo.connochie+scout@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title: Follow Your Favorites
    description: Scout makes it easy to follow Farcasters by username or FID. Stay organized by marking casts as read/unread.
    fontawesome_icon_name: user-plus

  - title: Built for Productivity
    description: Stay on top of conversations with offline support, saved casts, and app search, all in a native Swift app. 
    fontawesome_icon_name: bolt

  - title: Fully Customizable
    description: Tailor Scout to your needs with filters to hide replies, recasts, or media-only posts. 
    fontawesome_icon_name: magic

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#5f47a5"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#8A63D2"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#8A63D2"
feature_icons_background_color            : "#e2d8f4"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e2d8f4"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
